### ISSUE TITLE
RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by KID0031** [jokofa/torch_kmeans#5] opened 2023-04-13 16:32 UTC
Hi, when I run the code, I have this error, maybe it's a naive question but I can't solve it right now. 
I have data with batch_size=8, each batch has 3 points, and each point has dimension of 5, so the code is below. I want to seperate 3 points into two clusters, one contains 1 point and the other contains 2 points.
```
>>> model = ConstrainedKMeans()
>>> a = torch.rand(8, 3, 5)
>>> w = torch.ones(a.shape[:-1])
>>> w /= 2
>>> b = model(a, k=2, weights=w)
```
but I got this error
![image](https://user-images.githubusercontent.com/51467434/231825336-fb69d7f7-7ea6-4883-9c82-7d8e46f944e6.png)
Is there any ways to solve it? thanks :)

**Comment by jokofa** [comment] 2023-04-13 21:44
Thank you for using torch_kmeans and posting this issue.

For this  very small example the error is caused by n_trials being larger than the total number N of points in the instance, in your case 3. The default value for trials is 5, which is reasonably small for usual instances (which normally consist of hundreds or thousands of points) but causes the index out of range here. 

A quick fix will be to set the number of trials to 1 by specifying:

`model = ConstrainedKMeans(n_priority_trials_before_fall_back=1)`

However, I will ASAP push a fix to adapt the number of trials in case of very small instances automatically.

**Comment by KID0031** [comment] 2023-04-14 01:59
Thanks for the reply! it works now.

btw is there any way to disable the printing of `Full batch converged at iteration /100 with center shifts:`?  because I need to do clustering many times and there will be a lot of print like this.

**Comment by jokofa** [comment] 2023-04-14 07:17
Yes, simply set verbose=False in the constructor:

`model = ConstrainedKMeans(verbose=False)`

I will close this issue now, if there are any other problems feel free to (re-)open.

**Closed as completed** 2023-04-14 07:18 UTC
